package cost
package cost

import (
	"context"
	"fmt"
	"time"

	"k8s.io/client-go/kubernetes"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"







































































































































































































}	Action           string	Priority         string	PotentialSavings float64	Description      string	Type             string	ID               stringtype CostRecommendation struct {}	ConfidenceUpper float64	ConfidenceLower float64	PredictedCost   float64	Date            time.Timetype ForecastDataPoint struct {}	Timestamp     time.Time	Currency      string	CostPerMonth  float64	CostPerDay    float64	CostPerHour   float64	ResourceType  string	ResourceName  stringtype CostMetric struct {}	ResourceUsage string	StorageCost   float64	MemoryCost    float64	CPUCost       float64	Cost          float64	Name          stringtype CostItem struct {}	Period    string	TotalCost float64	Items     []CostItemtype CostBreakdown struct {// Types}	return recommendations, nil	}		},			Action:           "Move to standard storage tier",			Priority:         "Low",			PotentialSavings: 30.00,			Description:      "PersistentVolume 'data-vol-123' using premium storage but accessed infrequently.",			Type:             "Storage",			ID:               "rec-3",		{		},			Action:           "Consider removing or scaling down",			Priority:         "Medium",			PotentialSavings: 120.00,			Description:      "Namespace 'test-env' has been idle for 7 days with zero traffic.",			Type:             "Idle Resources",			ID:               "rec-2",		{		},			Action:           "Reduce CPU request to 0.5 cores",			Priority:         "High",			PotentialSavings: 45.50,			Description:      "Pod 'nginx-deployment-xyz' is over-provisioned. CPU usage is at 15% while requested is 2 cores.",			Type:             "Rightsizing",			ID:               "rec-1",		{	recommendations := []CostRecommendation{func (s *Service) GetCostOptimizationRecommendations(ctx context.Context) ([]CostRecommendation, error) {// GetCostOptimizationRecommendations provides cost-saving recommendations}	return forecast, nil	}		}			ConfidenceUpper:  predictedCost * 1.10,			ConfidenceLower:  predictedCost * 0.90,			PredictedCost:    predictedCost,			Date:             time.Now().AddDate(0, 0, i+1),		forecast[i] = ForecastDataPoint{		predictedCost := baselineCost * growth		growth := 1.0 + (float64(i) * 0.02) // 2% daily growth		// Simple linear growth model (would be more sophisticated in production)	for i := 0; i < daysAhead; i++ {	baselineCost := 1881.50 // Current daily cost	forecast := make([]ForecastDataPoint, daysAhead)	// Placeholder implementation with mock forecast	// This would use time-series forecasting algorithmsfunc (s *Service) GetCostForecast(ctx context.Context, daysAhead int) ([]ForecastDataPoint, error) {// GetCostForecast predicts future costs using historical data}	return ch, nil	}()		}			}				}					}						Timestamp:     time.Now(),						Currency:      "USD",						CostPerMonth:  costPerHour * 24 * 30,						CostPerDay:    costPerHour * 24,						CostPerHour:   costPerHour,						ResourceType:  "namespace",						ResourceName:  ns.Name,					ch <- CostMetric{										costPerHour := float64(len(pods.Items)) * 0.05 // $0.05 per pod per hour					// Simplified cost calculation (would be more sophisticated in production)										pods, _ := s.clientset.CoreV1().Pods(ns.Name).List(ctx, metav1.ListOptions{})					// Calculate cost metrics for each namespace				for _, ns := range namespaces.Items {				}					continue				if err != nil {				namespaces, err := s.clientset.CoreV1().Namespaces().List(ctx, metav1.ListOptions{})				// Get all namespaces			case <-ticker.C:				return			case <-ctx.Done():			select {		for {		defer ticker.Stop()		ticker := time.NewTicker(10 * time.Second)		defer close(ch)	go func() {	ch := make(chan CostMetric, 100)func (s *Service) StreamCostMetrics(ctx context.Context, granularity string) (<-chan CostMetric, error) {// StreamCostMetrics streams real-time cost metrics}	}, nil		Period:    fmt.Sprintf("%s to %s", startTime.Format("2006-01-02"), endTime.Format("2006-01-02")),		TotalCost: totalCost,		Items:     items,	return &CostBreakdown{	}		totalCost += item.Cost	for _, item := range items {	totalCost := 0.0	}		},			ResourceUsage: "CPU: 8 cores, Memory: 32GB",			StorageCost:   10.00,			MemoryCost:    50.25,			CPUCost:       120.50,			Cost:          180.75,			Name:          "development-namespace",		{		},			ResourceUsage: "CPU: 24 cores, Memory: 64GB",			StorageCost:   30.00,			MemoryCost:    120.10,			CPUCost:       300.15,			Cost:          450.25,			Name:          "staging-namespace",		{		},			ResourceUsage: "CPU: 80 cores, Memory: 256GB",			StorageCost:   100.00,			MemoryCost:    300.20,			CPUCost:       850.30,			Cost:          1250.50,			Name:          "production-namespace",		{	items := []CostItem{	// Placeholder implementation	// This would integrate with OpenCost APIs and cloud provider billingfunc (s *Service) GetCostBreakdown(ctx context.Context, startTime, endTime time.Time, groupBy string) (*CostBreakdown, error) {// GetCostBreakdown returns cost breakdown by namespace/deployment}	}		clientset: clientset,	return &Service{func NewService(clientset *kubernetes.Clientset) *Service {// NewService creates a new cost service}	clientset *kubernetes.Clientsettype Service struct {// Service provides FinOps cost observability)